export const GET_ERRORS = "GET_ERRORS";

/* PROFILE TYPES */
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REGISTER = "REGISTER";
export const Get_PROFILE = "GET_PROFILE";
export const Get_PROFILES = "GET_PROFILES";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const CREATE_PROFILE = "CREATE_PROFILE";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";
export const ADD_EDUCATION = "ADD_EDUCATION";
export const DELETE_EDUCATION = "DELETE_EDUCATION";

/* POST TYPES */
export const POST_LOADING = "POST_LOADING";
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const GET_POSTS_PER_USER = "GET_POSTS_PER_USER";
export const ADD_POST = "ADD_POST";
export const DELETE_POST = "DELETE_POST";
